//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApplication.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string Coord_Lat { get; set; }
        public string Coord_Long { get; set; }
    }
}
