//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApplication.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string alpha_2 { get; set; }
        public string alpha_3 { get; set; }
        public string country_code { get; set; }
        public string iso_3166_2 { get; set; }
        public string region { get; set; }
        public string sub_region { get; set; }
        public string region_code { get; set; }
        public string sub_region_code { get; set; }
    }
}
